# Here I experiment with codes that will be used in the main software

In [2]:
import numpy as np

In [112]:
#file ="/home/odin/work/gProj/clockSyncLEO/TimeStampData/13Nov18/10KM_2018-06-20T17-33-20-224820.txt"
#10KM_2018-06-20T17-48-20-224822
file ="/home/odin/work/gProj/clockSyncLEO/TimeStampData/13Nov18/10KM_2018-06-20T17-48-20-224822.txt"
raw_data  = np.fromfile(file, dtype='uint8')


In [113]:
print("bytes loaded: {0}".format(len(raw_data)))
raw_data = raw_data[24:]
bin_data = raw_data.reshape(int(raw_data.shape[0]/(8)),8)

bytes loaded: 86900736


In [114]:
print("Number of events: {0}".format(bin_data.shape[0]) )

Number of events: 10862589


In [115]:
bin_data [0:40]

array([[159,   0,   0,   0,  50,  23, 207, 190],
       [161,   0,   0,   0, 130, 137, 131,  53],
       [163,   0,   0,   0, 114,  18,  41,  32],
       [163,   0,   0,   0, 130, 137,  91,  66],
       [163,   0,   0,   0, 130,  13,  36,  84],
       [163,   0,   0,   0, 130, 159, 173, 214],
       [164,   0,   0,   0,  97, 128, 154,  23],
       [177,   0,   0,   0, 114, 130,  41, 217],
       [183,   0,   0,   0, 113,   0,  34,  95],
       [183,   0,   0,   0, 129,  13, 164, 135],
       [187,   0,   0,   0,  97, 128, 226, 209],
       [187,   0,   0,   0, 129, 157, 236, 241],
       [188,   0,   0,   0, 129, 137, 211, 102],
       [188,   0,   0,   0, 113,  18, 185, 139],
       [188,   0,   0,   0, 129, 159, 205, 192],
       [188,   0,   0,   0,  50,  23, 143, 241],
       [189,   0,   0,   0,  50, 159, 214,   4],
       [189,   0,   0,   0,  50,  23, 175,  27],
       [190,   0,   0,   0,  50,  23, 151, 134],
       [190,   0,   0,   0, 130, 159, 133, 158],
       [192,   0,   

In [111]:
#helper function
def create_word(barr):
    h = 0
    for b in reversed(barr):
        h = h << 8
        h = h | b
    #print (hex(h) )
    return h
    
def get_val(h, bitmask, r_shift ):
    val = (h&bitmask) >>r_shift
    return val

In [53]:
def extract_column(data, begin_byte, end_byte,pattern, right_shift):
    warr = map(create_word,data[:,begin_byte:end_byte])
    r = [get_val(w,pattern,right_shift) for  w in warr]

    return r

In [56]:
bin_data[-2:]

array([[227,  81,  23,   1, 114,  18,   9,  26],
       [227,  81,  23,   1, 194,   8,  75,  64]], dtype=uint8)

In [178]:
file ="/home/odin/work/gProj/clockSyncLEO/TimeStampData/13Nov18/10KM_2018-06-20T17-33-20-224820.txt"
#raw_data  = np.fromfile(file, dtype=np.uint64)

In [117]:
raw_data [:40]

array([12309478529212350622, 14422249564331311262, 15773329452542460062,
       13749233690901217439,  3856076897398030497,  2317403764094402723,
        4781566620822667427,  6062985850344439971, 15469195675782086819,
        1700812963385966756, 15648181806413381809,  6855042068142620855,
        9773951939002761399, 15123791652763730107, 17432481435020689595,
        7409416999098384572, 10068098718504059068, 13892935801907445948,
       17406156588326060220,   348641058264973501,  1994838663464222909,
        9698245826081456318, 11422711410589696190, 10666941133797458112,
        1977784894520033490,  7894554175319572691, 11163025730684584147,
        3827390634734387423,  6180521444330438879,  6859977844559184095,
        8022493691924971743, 15877052573438443743,  1902101798328467680,
        4225959206051643616, 13552914030040973547, 17559560721216307435,
         857961503112823020, 11410035072313589996,  1458910307807133936,
        3311286478021066992], dtype=uint64)

In [127]:
raw_data  = np.fromfile(file, dtype='<u8')

In [128]:
raw_data[0:40]

array([12309478529212350622, 14422249564331311262, 15773329452542460062,
       13749233690901217439,  3856076897398030497,  2317403764094402723,
        4781566620822667427,  6062985850344439971, 15469195675782086819,
        1700812963385966756, 15648181806413381809,  6855042068142620855,
        9773951939002761399, 15123791652763730107, 17432481435020689595,
        7409416999098384572, 10068098718504059068, 13892935801907445948,
       17406156588326060220,   348641058264973501,  1994838663464222909,
        9698245826081456318, 11422711410589696190, 10666941133797458112,
        1977784894520033490,  7894554175319572691, 11163025730684584147,
        3827390634734387423,  6180521444330438879,  6859977844559184095,
        8022493691924971743, 15877052573438443743,  1902101798328467680,
        4225959206051643616, 13552914030040973547, 17559560721216307435,
         857961503112823020, 11410035072313589996,  1458910307807133936,
        3311286478021066992], dtype=uint64)

In [147]:
x = raw_data[8]

In [151]:
x = np.right_shift(x, np.uint64(32))

In [152]:
x = x

In [153]:
x

109915

In [165]:
def _data_extractor(filename):
    """Reads raw timestamp into time and patterns vectors

    :param filename: a python file object open in binary mode
    :type filename: _io.BufferedReader
    :returns: Two vectors: timestamps, corresponding pattern
    :rtype: {numpy.ndarray(float), numpy.ndarray(uint32)}
    """
    with open(filename, 'rb') as f:
        data = np.fromfile(file=f, dtype='=I').reshape(-1, 2)
        # cast to uint64!!!
        t = ((np.uint64(data[:, 0]) << 17) + (data[:, 1] >> 15)) / 8.
        #t = ((np.uint64(data[:, 0]) << 17) + (data[:, 1] >> 15)) 
        p = data[:, 1] & 0xf
        return t, p


In [179]:
t,p = _data_extractor(file)

In [180]:
t

array([3.91143688e+06, 3.92457625e+06, 3.97981688e+06, ...,
       2.99915917e+11, 2.99916072e+11, 2.99916074e+11])

In [186]:
unique, counts = np.unique(p, return_counts=True)
d= dict(zip(unique, counts))


In [182]:
t[3000:3008]

array([87750984.75 , 87875461.   , 87976580.25 , 87977769.125,
       87979164.625, 87980942.5  , 88080189.375, 88131982.5  ])

In [183]:
221023043598 * 125e-12 /8

3.4534850562187502

In [184]:
b = t[0]
e = t[-1]

In [185]:
(e - b) * 1e-9 / 60

4.998536042402083

In [187]:
# {1: 4615196, 2: 6246245, 3: 1151} # 3 is the accidental coincidences. 
d

{1: 4634679, 2: 6429484, 3: 1181}

In [188]:
d[2]-d[1]

1794805

In [189]:
t.shape

(11065344,)

In [9]:
arr = np.arange(16)
arr
condition = np.mod(arr, 3)==0
condition
np.extract(condition, arr)
#array([0, 3, 6, 9])

array([ 0,  3,  6,  9, 12, 15])

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
condition

array([ True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True])

In [17]:
condition = np.bitwise_and(arr,2) == 2

In [18]:
np.extract(condition, arr)

array([ 2,  3,  6,  7, 10, 11, 14, 15])

In [21]:
g = np.zeros(5,dtype='float')

In [22]:
g

array([0., 0., 0., 0., 0.])

In [29]:
np.finfo(np.float)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [30]:
array = np.array([49, 51, 53, 56]) - 10

In [31]:
array

array([39, 41, 43, 46])

In [32]:
a = np.array([49, 51, 53, 56])

In [33]:
np.savetxt("foo.csv", a, delimiter=",")

In [34]:
b = [2,3,4,5]

In [36]:
np.savetxt("bar.csv", b, delimiter=",")