# Here I experiment with codes that will be used in the main software

In [43]:
import numpy as np
import scipy.io

In [2]:
#file ="/home/odin/work/gProj/clockSyncLEO/TimeStampData/13Nov18/10KM_2018-06-20T17-33-20-224820.txt"
#10KM_2018-06-20T17-48-20-224822
file ="/home/odin/work/gProj/clockSyncLEO/TimeStampData/13Nov18/10KM_2018-06-20T17-48-20-224822.txt"
raw_data  = np.fromfile(file, dtype='uint8')


In [3]:
print("bytes loaded: {0}".format(len(raw_data)))
raw_data = raw_data[24:]
bin_data = raw_data.reshape(int(raw_data.shape[0]/(8)),8)

bytes loaded: 86900736


In [4]:
print("Number of events: {0}".format(bin_data.shape[0]) )

Number of events: 10862589


In [5]:
bin_data [0:40]

array([[159,   0,   0,   0,  50,  23, 207, 190],
       [161,   0,   0,   0, 130, 137, 131,  53],
       [163,   0,   0,   0, 114,  18,  41,  32],
       [163,   0,   0,   0, 130, 137,  91,  66],
       [163,   0,   0,   0, 130,  13,  36,  84],
       [163,   0,   0,   0, 130, 159, 173, 214],
       [164,   0,   0,   0,  97, 128, 154,  23],
       [177,   0,   0,   0, 114, 130,  41, 217],
       [183,   0,   0,   0, 113,   0,  34,  95],
       [183,   0,   0,   0, 129,  13, 164, 135],
       [187,   0,   0,   0,  97, 128, 226, 209],
       [187,   0,   0,   0, 129, 157, 236, 241],
       [188,   0,   0,   0, 129, 137, 211, 102],
       [188,   0,   0,   0, 113,  18, 185, 139],
       [188,   0,   0,   0, 129, 159, 205, 192],
       [188,   0,   0,   0,  50,  23, 143, 241],
       [189,   0,   0,   0,  50, 159, 214,   4],
       [189,   0,   0,   0,  50,  23, 175,  27],
       [190,   0,   0,   0,  50,  23, 151, 134],
       [190,   0,   0,   0, 130, 159, 133, 158],
       [192,   0,   

In [6]:
#helper function
def create_word(barr):
    h = 0
    for b in reversed(barr):
        h = h << 8
        h = h | b
    #print (hex(h) )
    return h
    
def get_val(h, bitmask, r_shift ):
    val = (h&bitmask) >>r_shift
    return val

In [7]:
def extract_column(data, begin_byte, end_byte,pattern, right_shift):
    warr = map(create_word,data[:,begin_byte:end_byte])
    r = [get_val(w,pattern,right_shift) for  w in warr]

    return r

In [8]:
bin_data[-2:]

array([[227,  81,  23,   1, 114,  18,   9,  26],
       [227,  81,  23,   1, 194,   8,  75,  64]], dtype=uint8)

In [9]:
file ="/home/odin/work/gProj/clockSyncLEO/TimeStampData/13Nov18/10KM_2018-06-20T17-33-20-224820.txt"
#raw_data  = np.fromfile(file, dtype=np.uint64)

In [10]:
raw_data [:40]

array([159,   0,   0,   0,  50,  23, 207, 190, 161,   0,   0,   0, 130,
       137, 131,  53, 163,   0,   0,   0, 114,  18,  41,  32, 163,   0,
         0,   0, 130, 137,  91,  66, 163,   0,   0,   0, 130,  13,  36,
        84], dtype=uint8)

In [11]:
raw_data  = np.fromfile(file, dtype='<u8')

In [12]:
raw_data[0:40]

array([13561334090086482158,  9908220936027373807, 16763393425146904818,
        1158565856137969914,  2939162196438941946,  6382164111563686138,
       12984302626823733499,   982348158346461436, 15330816566853894396,
        2263084586852417789,   618856898468249854,  3772618742169600261,
       14574352498224529671, 15941631628686655751,  5959403054619951368,
       11257172169727148297,  5252779921092116749,  7087267793036378381,
        5848628220194193680,  9965796931135340819,  1685050914445984026,
       10620341975586439455,  4273387804051898658,  6555414154457383202,
       12701874506675781922,  9803383670550036774,   827115185431904551,
        2038732606459085095,  3797530097947246887,  5002830137478086951,
       10901526333335011623,  2228025627808629032, 16944124553745924393,
        1371090115073409322, 13920238535345963309,  7544828457423733041,
       15961058835213320502,  2211692318153507127, 11573139994432241975,
       10263175312749625656], dtype=uint64)

In [13]:
x = raw_data[8]

In [14]:
x = np.right_shift(x, np.uint64(32))

In [15]:
x = x

In [16]:
x

3569483889

In [17]:
def _data_extractor(filename):
    """Reads raw timestamp into time and patterns vectors

    :param filename: a python file object open in binary mode
    :type filename: _io.BufferedReader
    :returns: Two vectors: timestamps, corresponding pattern
    :rtype: {numpy.ndarray(float), numpy.ndarray(uint32)}
    """
    with open(filename, 'rb') as f:
        data = np.fromfile(file=f, dtype='=I').reshape(-1, 2)
        # cast to uint64!!!
        t = ((np.uint64(data[:, 0]) << 17) + (data[:, 1] >> 15)) / 8.
        #t = ((np.uint64(data[:, 0]) << 17) + (data[:, 1] >> 15)) 
        p = data[:, 1] & 0xf
        return t, p


In [18]:
t,p = _data_extractor(file)

In [19]:
t

array([3.91143688e+06, 3.92457625e+06, 3.97981688e+06, ...,
       2.99915917e+11, 2.99916072e+11, 2.99916074e+11])

In [20]:
unique, counts = np.unique(p, return_counts=True)
d= dict(zip(unique, counts))


In [21]:
t[3000:3008]

array([87750984.75 , 87875461.   , 87976580.25 , 87977769.125,
       87979164.625, 87980942.5  , 88080189.375, 88131982.5  ])

In [22]:
221023043598 * 125e-12 /8

3.4534850562187502

In [23]:
b = t[0]
e = t[-1]

In [24]:
(e - b) * 1e-9 / 60

4.998536042402083

In [25]:
# {1: 4615196, 2: 6246245, 3: 1151} # 3 is the accidental coincidences. 
d

{1: 4634679, 2: 6429484, 3: 1181}

In [26]:
d[2]-d[1]

1794805

In [27]:
t.shape

(11065344,)

In [28]:
arr = np.arange(16)
arr
condition = np.mod(arr, 3)==0
condition
np.extract(condition, arr)
#array([0, 3, 6, 9])

array([ 0,  3,  6,  9, 12, 15])

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
condition

array([ True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True])

In [31]:
condition = np.bitwise_and(arr,2) == 2

In [32]:
np.extract(condition, arr)

array([ 2,  3,  6,  7, 10, 11, 14, 15])

In [33]:
g = np.zeros(5,dtype='float')

In [34]:
g

array([0., 0., 0., 0., 0.])

In [35]:
np.finfo(np.float)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [36]:
array = np.array([49, 51, 53, 56]) - 10

In [37]:
array

array([39, 41, 43, 46])

In [38]:
a = np.array([49, 51, 53, 56])

In [39]:
np.savetxt("foo.csv", a, delimiter=",")

In [40]:
b = [2,3,4,5]

In [41]:
np.savetxt("bar.csv", b, delimiter=",")


In [44]:
a = [9,10,11,12,13]

In [45]:
scipy.io.savemat('test.mat', mdict={'len': 5,'begin': 9, 'end':13, 'data': a })